name: Crossbow
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml



jobs:        
  r-packages:
    runs-on: macos-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
      - name: Test
        shell: Rscript {0}
        run: |
          install.packages("arrow", repos = c("https://nightlies.apache.org/arrow/r", getOption("repos")), type = "mac.binary")
          
          packageVersion("arrow")
          arrow::arrow_info()
