name: Dev PR
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  macos11:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ github.base_ref }}"
          echo "${{ github.head_ref }}"
