name: Crossbow
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

permissions:
  contents: none

jobs:        
  r-packages:
    runs-on: ubuntu-latest
    steps:
      - run: touch test.file
      - uses: actions/upload-artifact@v2
        with:
          name: test-output
          path: test.file
