name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:
  cpr:
      name: job
      runs-on: macos-14
      steps:
        - uses: r-lib/actions/setup-r@v2
        - shell: sudo Rscript {0}
          run: |
             # get the mac-recipes version of openssl from CRAN
            source("https://mac.R-project.org/bin/install.R") 
            install.libs("openssl")
            
            # override our cmakes default setting of the brew --prefix as root dir to avoid version conflicts.
            if (Sys.info()[["machine"]] == "arm64"){
              cat("OPENSSL_ROOT_DIR=/opt/R/arm64\n", file=Sys.getenv("GITHUB_ENV"), append = TRUE)
            } else {
              cat("OPENSSL_ROOT_DIR=/opt/R/x86_64\n", file=Sys.getenv("GITHUB_ENV"), append = TRUE)
            }

