name: Dev PR
on:
  #push:
  workflow_dispatch:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run:   brew install \
                bison boost ccache double-conversion flex fmt gflags glog \
                icu4c libevent libsodium lz4 lzo ninja openssl protobuf@21 \
                range-v3 simdjson snappy thrift xz xsimd zstd
               brew link protobuf@21
