name: Dev PR
on:
  workflow_dispatch:
  push:
    branches: ['main']
    tags: [ 'v*.*.*' ]
    
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
