name: Dev PR
on:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir results/a
          touch number.txt
          touch results/something.json
          touch results/a/res.json
      - uses: actions/upload-artifact@v4
        with:
          name: results
          path: |
            number.txt
            results/
   get:
    runs-on: ubuntu-latest
    needs: 'test-source'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: results
          path: /tmp/artifacts
      - run: ls -R /tmp/artifacts
    
          
