name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:        
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update
          sudo apt install libboost-all-dev
      - run: |
          echo 'cmake_minimum_required(VERSION 3.14)
          project(test)
          set(BOOST_INCLUDE_LIBRARIES
          headers
          atomic
          context
          date_time
          filesystem
          program_options
          regex
          system
          thread)
          find_package(Boost 1.66.0 COMPONENTS ${BOOST_INCLUDE_LIBRARIES})' >> CMakeLists.txt
          cmake .
