name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  step1:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: "${{ github.token }}"
    strategy:
      matrix:
        v: ['centos', 'not-centos']
    steps:
      - uses: actions/checkout@${{ matrix.v == 'centos' && 'v3' || 'v4' }}
