name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml
      
permissions: 
  contents: read
jobs:        
  step1:
    runs-on: macos-latest
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

          
