name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:        
  macos11:
    runs-on: ubuntu-latest
    steps:
      - id: output
        run: |
          mkdir ccache
          touch ccache/afile
      - container: ubuntu:latest
        run: |
          ls -la
          ls -la ccache
