name: Dev PR
on:
  #push:
  workflow_dispatch:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - env:
          TEST: "${{ false && 'true' || ''}}"
        run: |
             find /usr -iname '*lz4*'

