name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:        
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "test=5" >> $GITHUB_ENV
  build2:
    needs: build
    name: test2
    runs-on: ubuntu-latest
    steps:
      - run: echo $test
