name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:        
  macos11:
    runs-on: ubuntu-latest
    steps:
      - id: output
        run: |
          mkdir ccache
          touch ccache/afile
      - run: |
          ccache -V || echo a
          cmake --version
          sudo apt update
          sudo apt install cmake ccache
