name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml
      
permissions: 
  contents: read
jobs:        
  step1:
    runs-on: ubuntu-latest
    steps:
       - shell: bash
         run: apt-get install -y libcurl4-openssl-dev libssl-dev

        
