name: Dev PR
on:
  pull_request:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  step1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: git rev-parse HEAD 
      - run: sleep 120
  step2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: git rev-parse HEAD 
