name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml
      
permissions: 
  contents: read
jobs:        
  blub:
    runs-on: ubuntu-latest
    steps:
      - run: |
          df -h .
          du -hs .
