name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml
      
permissions: 
  contents: read

jobs:        
  blub:
    runs-on: ubuntu-latest
      
    steps:
      - id: a
        run: |
          if [ "s" == "s" ]; then
            echo "true"
            exit 0
          fi

          echo "after if"
      - run: echo "${{ steps.a.outputs.b }}"
      - if: false
        uses: assignUser/stash/restore@main
        with:
          path: test_bin/
          key: test-sta/sh
          
      - if: false
        uses: assignUser/stash/save@main
        with:
          path: /usr/local/lib/node_modules
          key: test-stash-35/merge
