name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  macos11:
    runs-on: macos-11
    steps:
      - run: |
          brew update
          brew install python@3.11
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true
  macos12:
     runs-on: macos-12
     steps:
       - run: |
           brew update
           brew install python@3.11
         env:
           HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true      
