name: Dev PR
on:
  #push:
  workflow_dispatch:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: macos-14
    steps:
      - env:
          TEST: "true"
        run: |
             set -x
             echo "yes: ${{ env.TEST == 'true' && 'yes'}}"
             echo "nothing: ${{ env.TEST == 'tue' && 'yes'}}"
