name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  step1:
    runs-on: macos-11
    steps:
      - run: |
          brew install python@3.11
          brew update
          brew install --overwrite python@3.11
        env:
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: true
       
