name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:
  cpr:
      name: job
      runs-on: ubuntu-20.04
      steps:
        - id: fail
          run: |
            sudo sysctl vm.max_map_count
            sudo sysctl -w vm.max_map_count=67108864
            touch some_file
        - shell: docker run --rm -v .:/velox -w /velox ghcr.io/facebookincubator/velox-dev:centos8 /bin/bash -e {0}
          run: |
            ls
            touch anotherfile
            sysctl vm.max_map_count
        - run: ls
