name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:        
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: cmake --version
      - uses: actions/checkout@v4
        with:
          repository: 'facebookincubator/velox'
      - run: |
          source scripts/setup-ubuntu.sh
          cmake --version
      - run: make cmake BUILD_DIR=debug BUILD_TYPE=Debug
