name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  step1:
    runs-on: macos-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
      - shell: Rscript {0}
        run: |
          # install deps as binary
          install.packages("arrow")
          remove.packages("arrow")
          
          # install from source
          Sys.setenv(ARROW_R_DEV = TRUE, LIBARROW_BINARY= FALSE, FORCE_BUNDLED_BUILD = TRUE)
          install.packages("arrow")
