name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:
  cpr:
      name: job
      runs-on: ubuntu-20.04
      steps:
        - id: fail
          run: |
            var='> [!CAUTION]\nsome text\nwith\nnewlines and such'
            echo $var >> $GITHUB_STEP_SUMMARY
