name: Dev PR
on:
  #push:
  workflow_dispatch:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - id: blub
        timeout-minutes: 1
        run: sleep 70
      - if: ${{ !cancelled() }}
        run: echo "${{ steps.blub.conclusion }}"
