name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:        
  macos11:
    runs-on: ubuntu-latest
    steps:
      - id: output
        run: |
          jq '. |= keys' ${{github.event_path}}
