name: Dev PR
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  step1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ toJSON(github.event) }}
        id: test2
