name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml
      
permissions: 
  contents: read

jobs:        
  blub:
    runs-on: ubuntu-latest
      
    steps:
      - env:
          boom: "'$(echo boom)'"
        run: echo 
      - uses: actions/checkout@v4
      - if: false
        uses: assignUser/stash/restore@main
        with:
          path: test_bin/
          key: test-sta/sh
          
      - if: true
        uses: assignUser/stash/save@main
        with:
          path: /usr/local/lib/node_modules
          key: test-stash-35/merge
