name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  macos11:
    runs-on: macos-11
    steps:
      - run: sysctl -a | grep "avx|bmi|f16c"
  macos12:
    runs-on: macos-12
    steps:
      - run: sysctl -a | grep "avx|bmi|f16c"
