name: Dev PR
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  macos11:
    runs-on: ubuntu-latest
    steps:
      - id: output
        run: |
          echo "multi-line<<delim" >> $GITHUB_OUTPUT
          echo "{" >> $GITHUB_OUTPUT
          echo '"a_value":242' >> $GITHUB_OUTPUT
          echo "}" >> $GITHUB_OUTPUT
          echo "delim" >> $GITHUB_OUTPUT
      - run: |
          echo "${{ steps.output.outputs.multi-line }}"
