name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml
      
permissions: 
  contents: read
jobs:        
  step1:
    runs-on: macos-latest
    steps:
       - shell: bash
         env:
          PYTEST_ARGS: "-W error -W ignore:Setting\\scustom\\sClientSession:DeprecationWarning"
         run: |
           UNAME=`uname -s`
              if [ "$UNAME" = "Darwin" ] && [ $(sw_vers -productVersion) = "10.13" ]; then
                # avoid C++17 availability warnings on macOS < 11
                echo "-D_LIBCPP_DISABLE_AVAILABILITY"
              else;
              echo blub
              fi

        
