name: Crossbow
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

permissions:
  contents: read

jobs:        
  r-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: assignUser/test-repo-b@main
        with:
          explicit_secret: ${{ secrets.some_token }}
