name: Dev PR
on:
  #push:
  workflow_dispatch:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: macos-12
    steps:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
