name: Dev PR
on:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - shell: python
        env:
          title: ${{ github.event.pull_request.title }}
        run: |
          import re 
          import os
          title = os.environ["title"]
          match = re.search(r"^(.+?)(\(.+\))?: (.+)", title)
          if match is None:
            print("::error::Please follow conventional commit guidelines in [CONTRIBUTING.md](https://github.com/facebookincubator/velox/blob/main/CONTRIBUTING.md#commit-messages)")
            exit(1)
          else:
            exit(0)
