name: Dev PR
on:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: go-ubuntu-latest
          path: adbc/go/adbc/pkg
          merge-multiple: false
          repository: apache/arrow-adbc
          run-id: 11848882525
      - run: ls -R

          
