name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: macos-12
    steps:
      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'oldrel'
          
      - shell: Rscript {0}
        env:
          LIBARROW_BINARY: "false"
        run: |
            install.packages('arrow')



