name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml
      
permissions: 
  contents: read
jobs:        
  step1:
    runs-on: macos-12
    steps:
      - run: |
          wget -O pc.tar.xz https://mac.r-project.org/bin/darwin17/x86_64/pkgconfig-0.29.2-darwin.17-x86_64.tar.xz
          tar -xzf pc.tar.xz
          echo "PKG_CONFIG=`pwd`/usr/local/bin/pkg-config"         
      - run: $PKG_CONFIG --version || blub
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - run: |
          brew install openssl@1.1 || echo blub
          echo "OPENSSL_ROOT_DIR=`brew --prefix openssl@1.1`" >> $GITHUB_ENV
          brew uninstall pkgconfig
      - uses: actions/checkout@v3
        with:
          repository: assignUser/arrow
          ref: debug-pc-error
          path: arrow
      - run: |
          cd arrow/r
          Rscript tools/update-checksums.R 14.0.0
          make build
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - shell: Rscript {0}
        run: |
          install.packages('arrow')
          remove.packages('arrow')
          install.packages('arrow/r/arrow_14.0.0.1.tar.gz')  
