name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  macos11:
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir base
          echo "changed file" >> base/test.R
      - uses: actions/checkout@v3
        with:
          path: base
      - uses: actions/upload-artifact@v3
        with:
          path: velox
          name: velox
  test:
    needs: macoss11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: velox
          
      - run: |
          ls 
          ls velox
