name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:        
  macos11:
    runs-on: ubuntu-latest
    steps:
      - id: output
        run: |
          echo "${{ github.even_name != 'push' || 'blue' }}"
