name: Dev PR
on:
  #push:
  workflow_dispatch:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: macos-12
    steps:
      - run: |
          a_var=(1 2)
          echo "a_var=$a_var" >> $GITHUB_ENV
      - run: |
          echo ${a_var[@]}
          a_var+=(5)
          echo "a_var=$a_var" >> $GITHUB_ENV
      - run: |
          echo ${a_var[@]}
          

