name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  r-packages:
    runs-on: macos-11
    env:
      dts: 8
    steps:
      - run: brew install sccache
