name: Crossbow
on:
  workflow_dispatch:
  push:
    branches:
      - "*-github-*"



jobs:
  test-linux-binary:
    name: Test binary ${{ matrix.image }}
    runs-on: ubuntu-latest
    container: ${{ matrix.image }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - "rhub/ubuntu-gcc-release" # ubuntu-20.04 (focal)
          - "rstudio/r-base:4.1-bionic"
          - "rstudio/r-base:4.2-centos7"
          - "rocker/r-ver:3.6.3" # for debian:buster (10)
          - "rocker/r-ver" # ubuntu-20.04
          - "rhub/fedora-clang-devel" # tests distro-map.csv, mapped to ubuntu-18.04
          - "rocker/r-ubuntu:22.04" # tests openssl3 compatibility
    steps:
      - name: Install system requirements
        shell: bash
        run: |
          if [ "`which dnf`" ]; then
            dnf install -y libcurl-devel openssl-devel python3
          elif [ "`which yum`" ]; then
            yum install -y libcurl-devel openssl-devel python3
          elif [ "`which zypper`" ]; then
            zypper install -y libcurl-devel libopenssl-devel python3
          else
            apt-get update
            apt-get install -y libcurl4-openssl-dev libssl-dev python3
          fi

          # Add R-devel to PATH
          echo "/opt/R-devel/bin" >> $GITHUB_PATH
          # Explicitly install Python as not all container might have it  
      - run: python3 -m http.server 8080 --bind localhost &
      - run: curl localhost:8080
