name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:
  cpr:
      name: cpr direcct
      runs-on: ubuntu-22.04
      env:
        blub: > 'this
                 is 
                 oneline'
              
      steps:
        - run: echo $blub
      
