name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  step1:
    runs-on: ubuntu-latest
    steps:
        - name: Trigger pkgcheck-action build
          uses: actions/github-script@v5
          with:
            github-token: ${{ secrets.ADBC_DISPATCH }}
            script: |
              await github.rest.actions.createWorkflowDispatch({
                owner: 'assignUser',
                repo: 'test-repo-b',
                workflow_id: 'test1.yaml',
                ref: 'main',
              });
