name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  step1:
    runs-on: macos-12
    steps:
      - run: |
          brew install python@3.11
