name: Dev PR
on:
  #push:
  workflow_dispatch:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: macos-14
    strategy:
      matrix:
        blub:
          - {a: "a", b: "b"}
    steps:
      - uses: r-lib/actions/setup-r@v2
      - run: echo "${{ true && fromat("{0} + {2}", matrix.blub.a, matrix.blub.b)}}"
