name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  macos11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: facebookincubator/velox
      - uses: actions/checkout@v3
        with:
          repository: assignUser/velox
