name: Crossbow
on:
  workflow_dispatch:
  push:
    branches:
      - "*-github-*"



jobs:
   r-packages:
    name: ${{ matrix.platform }} ${{ matrix.r_version.r }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows-latest
          - macos-latest
          - ubuntu-latest
          # This is newer than what CRAN builds on, but Travis is no longer an option for us, so...

          # - devops-managed # No M1 until the runner application runs native
        r_version:
          - { rtools: 40, r: "4.1" }

    steps:
      - name: Serve repo via localhost
        shell: bash
        run: python3 -m http.server 8080 --bind localhost &
      - run: echo "Next Step"
