name: Dev PR
on:
  #push:
  workflow_dispatch:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: macos-14
    steps:
      - env:
          TEST: "${{ false && 'true' || ''}}"
        run: |
             set -x
             echo "yes: $TEST"

