name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:        
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt update
          sudo apt install libboost-all-dev
      - shell: cmake -P {0}
        run: |
          cmake_minimum_required(VERSION 3.14)
          enable_language(C CXX)
          set(BOOST_INCLUDE_LIBRARIES
          headers
          atomic
          context
          date_time
          filesystem
          program_options
          regex
          system
          thread)
          find_package(Boost 1.66.0 COMPONENTS ${BOOST_INCLUDE_LIBRARIES})
