name: Dev PR
on:
  #push:
  workflow_dispatch:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        blub:
          - {a: "a", b: "b"}
    steps:
      - run: echo "${{ true && format('{0} + {1}', matrix.blub.a, matrix.blub.b)}}"
