name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:        
  step1:
    name: Another Name
    runs-on: ubuntu-latest
    steps:
      - env:
          ARGS: "/usr/* /tmp/*"
        run: |
          echo $ARGS
          set -f 
          echo $ARGS
          
      

                    
