name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  step1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "# Embedded Screenshot" >> $GITHUB_STEP_SUMMARY
          wget https://i.imgur.com/qpDgH7Q.jpeg
          IMAGE=$(base64 qpDgH7Q.jpeg)
          echo "![Hello World](data:image/png;base64,$IMAGE)" >> $GITHUB_STEP_API
          
