name: Dev PR
on:
  #push:
  workflow_dispatch:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: macos-12
    steps:
      - name: Setup tmate session
        env:
          GH_TOKEN: ${{ github.token }}
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: false
