name: Crossbow
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml



jobs:        
  r-packages:
    runs-on: windows-latests
    steps:
     - uses: r-lib/actions/setup-r@v2
       with:
          rtools-version: 40
          r-version: "4.0"
          Ncpus: 2
     - name: Get sccache
       shell: bash
       run: |
          SCCACHE_BUILD=pc-windows-msvc
          SCCACHE_URL=https://github.com/mozilla/sccache/releases/download/v0.3.0/sccache-v0.3.0-x86_64-$SCCACHE_BUILD.tar.gz

          # Download archive and checksum
          curl -L $SCCACHE_URL --output sccache.tar.gz
          curl -L $SCCACHE_URL.sha256 --output sccache.tar.gz.sha256

          SCCACHE_ARCHIVE=sccache.tar.gz
          echo "$(cat $SCCACHE_ARCHIVE.sha256) $SCCACHE_ARCHIVE" | sha256sum --check --status

          mkdir -p sccache
          tar -xzvf $SCCACHE_ARCHIVE --strip-component=1 --directory sccache
          echo "$(pwd)/sccache" >> $GITHUB_PATH
     - name: test
       shell: bash
       run: |
        which sccache
