name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml
      
permissions: 
  contents: read
jobs:        
  get:
    runs-on: ubuntu-latest
    steps:
      - name: "Full step is evaluated"
        if: ${{ env.var }}
        env:
          var: true
        run: echo The full step is evaluated before if is checked.      
      - name: "if is evaluated directly"
        if: ${{ !env.var }}
        env:
          var: true
        run: echo If is evaluated before the rest of the step.
