name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml
      
permissions: 
  contents: read
jobs:        
  step1:
    runs-on: macos-13
    steps:
      - run: echo "alias pkg-config='exit 1'">>$GITHUB_ENV
      - run: which pkg-config
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
      - run: |
          brew install openssl@1.1 || echo blub
          echo "OPENSSL_ROOT_DIR=`brew --prefix openssl@1.1`" >> $GITHUB_ENV
      - shell: Rscript {0}
        run: |
          install.packages('arrow')
          remove.packages('arrow')
          install.packages('arrow', type = 'source')  
