name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:
  cpr:
      name: job
      runs-on: ubuntu-latest
      steps:
        - uses: r-lib/actions/setup-r@v2
        - shell: Rscript {0}
          run: |
            if (!requireNamespace("MASS", quietly = TRUE))
              install.packages("MASS")

            library(MASS)

