name: Dev PR
on:
  pull_request:

jobs:
  get:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: results
          run-id: 12190195553
          merge-multiple: true
          path: /tmp/artifacts
      - run: ls -R /tmp/artifacts
    
          
