name: Dev PR
on:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - run: touch blub.txt
      - uses: actions/upload-artifact@v4
        with:
          name: blub
          path: blub.txt
      - uses: actions/download-artifact@v4
        with:
          name: blub
          path: a/dir
     - run: ls -R

          
