name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:        
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - run: python3 -c "import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX'))"      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python3 -c "import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX'))"
