name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:
  cpr:
      name: job
      runs-on: ubuntu-22.04
      outputs:
        fail: ${{ steps.fail.outputs.fail }}
      steps:
        - id: fail
          run: |
            echo "fail=false" >> $GITHUB_OUTPUT
  job:
      name: job2
      needs: cpr
      runs-on: ubuntu-22.04
      if: ${{ needs.cpr.outputs.fail }}
      steps:
        - id: fail
          run: |
            echo "should have been skipped"
