name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:
  build_wheels:
    name: Build wheels
    runs-on: macos-11
    env:
      PATH: ¨/some/dir;$PATH"
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.1
      - shell: Rscript {0}
        run: |
          install.packages("arrow", type = "binary")
          remove.packages("arrow")
          install.packages("arrow", type = "source")
