name: Dev PR
on:
  workflow_dispatch:
  pull_request:
     types:
      - opened
      - edited
      - synchronize
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  step1:
    runs-on: ubuntu-latest
    steps:
        - run: echo "${{ github.event.action }}"
