name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  step1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "del_prs=1 2 3" >> $GITHUB_OUTPUT
        id: test
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
