name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml
      
permissions: 
  contents: read
jobs:        
  get:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cpp_version: [ "15.0.0" , "14.0.2",  "13.0.0"  ]
    steps:
      - run: echo ${{ matrix.cpp_version }}
