name: Dev PR
on:
  #push:
  workflow_dispatch:
  pull_request:

jobs:
   test-source:
    name: Test
    runs-on: macos-14
    steps:
      - run: Rscript -e 'install.packages("arrow"); arrow::arrow_info()'
