name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  r-packages:
    runs-on: ubuntu-latest
    env:
      dts: 8
    steps:
      - run: echo dts
        if: env.dts > 0
      - run: echo dts
        if: env.dts
      - run: echo dts
        if: env.dvt > 0
      - run: echo dts
        if: env.dvt
