name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:
  build_wheels:
    name: Build wheels
    runs-on: macos-11
    env:
      PATH: ¨/some/dir;$PATH"
    steps:
      - run: Rscript -e "install.packages('arrow')"
