name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  r-packages:
    runs-on: macos-11
    steps:
      - run: |
          echo $(which tar)
          echo $(which gzip)
          brew install pigz
          echo $(which pigz)
          ln -s /usr/bin/pigz /usr/bin/gzip
          ln -s /usr/bin/unpigz /usr/bin/gunzip
          echo $(which gzip)
          brew install llvm@15
    #  - uses: actions/checkout@v3
    #    with:
    #      repository: apache/arrow
    #      depth: 1
    #  - name: Install Homebrew Dependencies
    #    shell: bash
   #     run: |
    #      rm -f /usr/local/bin/2to3
    #      brew update --preinstall
     ##     brew install --overwrite git
      #    echo $(brew --cache)
      #- name: test brew
      #  run: |
      #    brew bundle -vd --file=cpp/Brewfile
      #    brew bundle -vd --file=c_glib/Brewfile
        

