name: Dev PR
on:
  workflow_dispatch:
  pull_request:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:        
  macos11:
    runs-on: ubuntu-latest
    steps:
      - run: |
          merge_base=$(true) || { echo "::error::Failed to find merge base" && exit 1 }
      - run: |
          merge_base=$(false) || { echo "::error::Failed to find merge base" && exit 1 }

