name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml

jobs:
  build_wheels:
    name: Build wheels
    runs-on: macos-latest
    steps:
      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false
      - shell: Rscript {0}
        run: |
          install.packages("arrow", type = "mac.binary")
          remove.packages("arrow")
          install.packages("arrow", type = "source")
