name: Dev PR
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/crossbow-test.yaml
permissions:
  checks: write
  statuses: write
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.checks.create({
              owner: "assignUser",
              repo: "test-repo-a",
              name: 'mighty_readme',
              head_sha: '${{github.sha}}',
              status: 'in_progress',
              external_id: '42',
              output: {
                title: 'Mighty Readme report',
                summary: '',
                text: ''
              },
            });
