name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:
  get:
    runs-on: ubuntu-latest
    outputs:
      bla: ${{ fromJSON(steps.test.outputs.bla) }}
    steps:
      - id: test
        run: |
          echo "bla=false" >> "$GITHUB_OUTPUT"
      - if: ${{ steps.test.outputs.bla }}
        run: echo Shouldnt run but step outputs are strings
  job2:
    needs: get
    if: ${{ needs.get.outputs.bla }}
    runs-on: ubuntu-latest
    steps:
      - run: echo Shouldnt run but job outputs are strings
                    
