name: Dev PR
on:
  #workflow_dispatch:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  #push:
    #paths:
      #- .github/workflows/crossbow-test.yaml

permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.event.number }}
  cancel-in-progress: true
jobs:        
  r-packages:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sleep 5
          echo "${{ github.event.number }}"
