name: Dev PR
on:
  push:
  workflow_dispatch:
 # pull_request:

jobs:
   test-source:
    name: Test
    runs-on: macos-12
    steps:
      - run: echo "triggered by ${{github.event_name}} for ${{ github.sha }} on ${{ github.ref}}"


