name: Dev PR
on:
  workflow_dispatch:
  pull_request:

jobs:
  cpr:
      name: job
      runs-on: ubuntu-20.4
      steps:
        - id: fail
          run: |
            sudo sysctl vm.max_map_count
            sudo sysctl -w vm.max_map_count=67108864
  job:
      name: job2
      runs-on: ubuntu-22.04
      container: ghcr.io/facebookincubator/velox-dev:centos8
      steps:
        - id: fail
          run: |
            sysctl vm.max_map_count
            sysctl -w vm.max_map_count=67108864
