name: MacCrossbow
on:
  workflow_dispatch:
    inputs:
     boolean:
       type: bool
       default: false
     something:
       type: choice
       options:
         - "first"
         - "second"


jobs:
  build:
    name: Test empty inputs
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.something }}"
