name: Mac
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest
    steps:
        - name: Detect M1
          run: |
            if [[ $(uname -m) == 'arm64' ]]; then
              echo "On M1"
            fi
            arch -arm64 brew install rclone
