name: MacCrossbow
on:
  workflow_dispatch:
    inputs:
     something:
       description: 'An input with default'
       default: 'default'


jobs:
  build:
    name: Test empty inputs
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.something }}"
