name: Mac
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-latest
    steps:
        - name: Detect M1
          run: |
            arch
            arch -arm64 brew install rclone
