name: Mac
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
        - name: Detect M1
          run: |
            echo $(uname -m)
            if [[ $(uname -m) == 'arm64' ]]; then
              echo "ON_M1=true" >> $GITHUB_ENV
            fi
        - uses: assignUser/actions/setup-r@detect-m1
          with:
            r-version: 4.1
            rtools-version: 40
            Ncpus: 2