name: Nightly gh_pages test

on:
  workflow_dispatch:
    inputs:
      version: 
        description: 'Version string'
        required: true
        default: '20220505'

jobs:
  source:
    name: Source Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout arrow
        uses: actions/checkout@v3
        with:
          repository: apache/arrow
          path: arrow

      - name: Modify version
        shell: bash
        run: |
          cd arrow/r
          sed -i.bak -E -e \
            's/(^Version: [0-9]+\.[0-9]+\.[0-9]+).*$/\1.'"${{ github.event.inputs.version }}"'/' \
            DESCRIPTION
          head DESCRIPTION
          rm -f DESCRIPTION.bak

          cp ../dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb tools/apache-arrow.rb
          
          # Pin the git commit in the formula to match
          cd tools
          sed -i.bak -E -e 's/arrow.git"$/arrow.git", :revision => "'"$(git rev-list -n 1 HEAD)"'"/' apache-arrow.rb
          rm -f apache-arrow.rb.bak
      - name: Cache repo
        uses: actions/cache@v3
        id: cache-repo
        with:
          path: repo
          key: test

      - name: Checkout package repo
        if: steps.cache-repo.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: repo

      - name: Update repo
        if: steps.cache-repo.outputs.cache-hit == 'true'
        shell: bash
        run: |
          cd repo
          git pull origin gh-pages

      - uses: r-lib/actions/setup-r@v2
        with:
          install-r: false

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          dependencies: '"hard"'
          cache: 2
          packages: |
            github::eddelbuettel/drat

      - name: Build R source package
        shell: bash
        run: |
          cd arrow/r
          # Copy in the Arrow C++ source
          make sync-cpp
          R CMD build --no-build-vignettes .

      - name: Insert src package
        shell: Rscript {0}
        run: |
          pkg <- list.files("arrow/r", "arrow_.+\\.tar\\.gz", full.names = TRUE)
          stopifnot(length(pkg) == 1)
          drat::insertPackage(pkg,
                              repodir = "${{ github.workspace }}/repo",
                              action = "prune",
                              location = "gh-pages"
          )
      - name: Commit & Push
        id: nightly-src-pkg
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd repo
          
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          gh auth setup-git -h github.com

          git add -A
          git commit -m"Nightly Src Package - ${{ github.event.inputs.version }}"
          git push
  linux-cpp:
    name: C++ Binary ${{ matrix.config.os }}-${{ matrix.config.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu, version: "18.04", r: "3.6" }
          - { os: centos, version: "7" }
    env:
      VERSION: ${{ matrix.config.version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache repo
        uses: actions/cache@v3
        id: cache-repo
        with:
          path: repo
          key: test

      - name: Checkout package repo
        if: steps.cache-repo.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: repo

      - name: Update repo
        if: steps.cache-repo.outputs.cache-hit == 'true'
        shell: bash
        run: |
          cd repo
          git pull origin gh-pages

      - name: Checkout arrow
        uses: actions/checkout@v3
        with:
          repository: apache/arrow
          path: arrow

      - name: Modify version
        shell: bash
        run: |
          cd arrow/r
          sed -i.bak -E -e \
            's/(^Version: [0-9]+\.[0-9]+\.[0-9]+).*$/\1.'"${{ github.event.inputs.version }}"'/' \
            DESCRIPTION
          head DESCRIPTION
          rm -f DESCRIPTION.bak

          cp ../dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb tools/apache-arrow.rb
          
          # Pin the git commit in the formula to match
          cd tools
          sed -i.bak -E -e 's/arrow.git"$/arrow.git", :revision => "'"$(git rev-list -n 1 HEAD)"'"/' apache-arrow.rb
          rm -f apache-arrow.rb.bak

      - name: Build libarrow
        shell: bash
        run: |
          cd linux
          docker-compose build ${{ matrix.config.os }}
          docker-compose run ${{ matrix.config.os }}

      - name: Bundle and upload
        shell: bash
        run: |
          cd arrow/r
          VERSION=$(grep ^Version DESCRIPTION | sed s/Version:\ //)
          export PKG_FILE="arrow-${VERSION}.zip"
          cd libarrow/dist
          # These files were created by the docker user so we have to sudo to get them
          sudo -E zip -r $PKG_FILE lib/ include/
          export REPO_PATH=${{ github.workspace }}/repo/libarrow/bin/${{ matrix.config.os }}-${{ matrix.config.version }}

          sudo mkdir -p $REPO_PATH
          sudo mv -f $PKG_FILE $REPO_PATH
      
      - name: Commit & Push
        id: nightly-nix-cpp
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd repo
          
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          gh auth setup-git -h github.com

          git add -A
          git commit -m"Nightly Src Package - ${{ github.event.inputs.version }}"
          git push
      - run: ls -lR --block-size=M repo

  windows-cpp:
    name: C++ Binary Windows RTools (40 only)
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf false
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout arrow
        uses: actions/checkout@v3
        with:
          repository: apache/arrow
          path: arrow

      - name: Cache repo
        uses: actions/cache@v3
        id: cache-repo
        with:
          path: repo
          key: test

      - name: Checkout package repo
        if: steps.cache-repo.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: repo

      - name: Update repo
        if: steps.cache-repo.outputs.cache-hit == 'true'
        shell: bash
        run: |
          cd repo
          git pull origin gh-pages

      - name: Modify version
        shell: bash
        run: |
          cd arrow/r
          sed -i.bak -E -e \
            's/(^Version: [0-9]+\.[0-9]+\.[0-9]+).*$/\1.'"${{ github.event.inputs.version }}"'/' \
            DESCRIPTION
          head DESCRIPTION
          rm -f DESCRIPTION.bak

          cp ../dev/tasks/homebrew-formulae/autobrew/apache-arrow.rb tools/apache-arrow.rb
          
          # Pin the git commit in the formula to match
          cd tools
          sed -i.bak -E -e 's/arrow.git"$/arrow.git", :revision => "'"$(git rev-list -n 1 HEAD)"'"/' apache-arrow.rb
          rm -f apache-arrow.rb.bak

      - uses: r-lib/actions/setup-r@v2
        with:
          rtools-version: 40
          r-version: "4.0"
          Ncpus: 2

      - name: Build Arrow C++ with rtools40
        shell: bash
        env:
          ARROW_HOME: "arrow"
        run: arrow/ci/scripts/r_windows_build.sh
      - name: Commit & Push
        id: nightly-win-cpp
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(grep ^Version arrow/r/DESCRIPTION | sed s/Version:\ //)
          cd build
          
          sudo mkdir -p ../repo/libarrow/bin/windows
          sudo mv arrow-$VERSION.zip ../repo/libarrow/bin/windows
          cd ../repo
          
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          gh auth setup-git -h github.com

          git add -A
          git commit -m"Nightly Src Package - ${{ github.event.inputs.version }}"
          git push
      - run: ls -lR --block-size=M repo
  r-packages:
    needs: [source, windows-cpp]
    name: ${{ matrix.platform }} ${{ matrix.r_version.r }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - windows-latest
          # This is newer than what CRAN builds on, but Travis is no longer an option for us, so...
          - macos-10.15
        r_version:
          - { rtools: 40, r: "4.1" }
          - { rtools: 42, r: "4.2" }
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache repo
        uses: actions/cache@v3
        id: cache-repo
        with:
          path: repo
          key: test

      - name: Checkout package repo
        if: steps.cache-repo.outputs.cache-hit != 'true'
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: repo

      - name: Update repo
        if: steps.cache-repo.outputs.cache-hit == 'true'
        shell: bash
        run: |
          cd repo
          git pull origin gh-pages

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r_version.r }}
          rtools-version: ${{ matrix.r_version.rtools }}
          Ncpus: 2
      - name: Build and insert
        shell: Rscript {0}
        run: |
          on_windows <- tolower(Sys.info()[["sysname"]]) == "windows"

          # Install dependencies by installing (yesterday's) binary, then removing it
          install.packages(c("arrow", "cpp11"),
            type = "binary",
            repos = c("https://assignUser.github.io/test-repo-a", "https://cloud.r-project.org")
          )
          remove.packages("arrow")

          # Build
          Sys.setenv(MAKEFLAGS = paste0("-j", parallel::detectCores()))
          INSTALL_opts <- "--build"
          if (!on_windows) {
            # Windows doesn't support the --strip arg
            INSTALL_opts <- c(INSTALL_opts, "--strip")
          }

          install.packages("arrow",
            type = "source",
            repos = "https://assignUser.github.io/test-repo-a",
            INSTALL_opts = INSTALL_opts
          )

          # Test
          library(arrow)
          read_parquet(system.file("v0.7.1.parquet", package = "arrow"))

          # Upload
          pkg <- list.files(".", "^arrow_", full.names = TRUE)
          stopifnot(length(pkg) == 1)
          drat::insertPackage(pkg,
                              repodir = "${{ github.workspace }}/repo",
                              action = "prune",
                              location = "gh-pages"
          )        
      - name: Commit & Push
        id: nightly-bin-pkg
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(grep ^Version arrow/r/DESCRIPTION | sed s/Version:\ //)
          cd build
          
          sudo mkdir -p ../repo/libarrow/bin/windows
          sudo mv arrow-$VERSION.zip ../repo/libarrow/bin/windows
          cd ../repo
          
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          gh auth setup-git -h github.com

          git add -A
          git commit -m"Nightly Src Package - ${{ github.event.inputs.version }}"
          git push
      - run: ls -lR --block-size=M repo
