name: Build Windows Base
on:
  workflow_dispatch:
    inputs:
     vcpkg-version:
       description: 'VCPKG Version to use in building the images.'
       required: true
       default: ''
     arrow-repo:
       description: 'Repository to checkout arrow from.'
       required: true
       default: 'apache/arrow'
     arrow-ref:
       description: 'Ref to checkout from arrow-repo.'
       required: true
       default: 'master'

jobs:
  build:
    name: "Build Windows images"
    runs-on: windows-2019
    permissions:
      contents: read
      packages: write
    env:
      # Turned on by default in .env but Windows does not support Buildkite
      # BUILDKIT_INLINE_CACHE: 1
      DOCKER_BUILDKIT: 0
      # archery uses this environment variable
      PYTHON: "3.10"
      # this is a private repository at the moment (mostly because of licensing
      # consideration of windows images with visual studio), but anyone can
      # recreate the image by manually building it via:
      # `archery build python-wheel-windows-vs2017`
      # note that we don't run docker build since there wouldn't be a cache hit
      # and rebuilding the dependencies takes a fair amount of time
      REPO: ghcr.io/assignuser/test-repo-a

    steps:
      - name: Checkout Arrow
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: arrow
          repository: apache/arrow
          submodules: recursive

      - name: Login to GitHub Container Registry
        shell: bash
        run: echo ${{secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Archery
        shell: bash
        run: pip install -e arrow/dev/archery[all]

      # - name: Fix .env
      #   shell: pwsh
      #   run: (Get-Content arrow/.env) -Replace '^DOCKER_BUILDKIT=1', 'DOCKER_BUILDKIT=0' -Replace '^REPO=.+$', 'REPO=${{ env.REPO }}' | Set-Content arrow/.env

      - name: Build image
        shell: cmd
        run: archery docker build --no-pull python-wheel-windows-vs2017

      - name: Push Image
        shell: cmd
        run: archery docker push python-wheel-windows-vs2017
