name: test known hosts

on: 
  workflow_run:
    workflows: ["Dev PR"]
    types:
      - completed


jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "test=5" >> $GITHUB_ENV 
  build2:
    name: test2
    runs-on: ubuntu-latest
    steps:
      - run: echo $test
