name: dispatch-test

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - run: echo "::warning file=R\lint_me.R,line=3,col=1,Put spaces around all infix operators."
       - run: echo "::warning file=R\lint_me.R,line=3,col=1::Put spaces around all infix operators."
       - run: echo "::warning file=R/lint_me.R,line=3,col=1::Put spaces around all infix operators."
       - run: echo "::warning file=R\lint_me.R,line=3,col=1,Put spaces around all infix operators.::"
       
