name: dispatch-test

on:
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger pkgcheck-action build
        run: |
          echo "::add-mask::Mona The Octocat"
          echo "Mona"
          echo "The"
          echo "Mona the Octocat"
          echo "::warning ::Something with a%0A newline!"
        shell: bash
