name: dispatch-test

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
  
jobs:
  test:
    runs-on: windows-latest
   
    steps:
      - id: s1
        run: |
         echo $PSVersionTable
         echo "some cool content" | Add-Content -Path test.txt 
         type test.txt

