name: dispatch-test

on:
  workflow_dispatch:
  pull_request:
  
jobs:
  test:
    runs-on: windows-latest
   
    steps:
      - id: s1
        run: |
         echo $PSVersionTable
         Add-Content -Path test.txt -Value 'End of file'
         type test.txt

