name: WebDav
on:
  workflow_dispatch:

jobs:
  # test-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: | 
  #         sudo apt update && sudo apt install davfs2
  #         mkdir nightly
  #         sudo bash -c 'echo "https://nightly.wujciak.de:8080 ${{ secrets.ASF_USER }} ${{ secrets.ASF_KEY }}" >> /etc/davfs2/secrets'
  #         sudo mount -t davfs https://nightly.wujciak.de:8080 nightly -o rw
  #         ls -la nightly
  test-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up keychain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ASF_USER: ${{ secrets.ASF_USER }}
          ASF_KEY: ${{ secrets.ASF_KEY }}
        run: bash fix-keychain.sh
        #security set-key-partition-list -S apple-tool:,apple: -s -k actions build.keychain
      - run: |
          sudo mkdir /Volumes/nightly
          sudo mount -t webdav https://nightly.wujciak.de:8080 /Volumes/nightly
          ls -la /Volumes/nightly