name: WebDav
on:
  push:
  workflow_dispatch:

jobs:
  # test-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: | 
  #         sudo apt update && sudo apt install davfs2
  #         mkdir nightly
  #         sudo bash -c 'echo "https://nightly.wujciak.de:8080 ${{ secrets.ASF_USER }} ${{ secrets.ASF_KEY }}" >> /etc/davfs2/secrets'
  #         sudo mount -t davfs https://nightly.wujciak.de:8080 nightly -o rw
  #         ls -la nightly
  test-mac:
    runs-on: macos-latest
    steps:
      - run: brew install --cask macfuse
      - run: curl https://rclone.org/install.sh | sudo bash
      - name: Configure rclone
        env:
          PW: ${{ secrets.ASF_KEY }}
          USER: ${{ secrets.ASF_USER }}
        run: |
          echo "[nightly]
          type = webdav
          url = https://nightly.wujciak.de:8080
          vendor = other
          user = $USER
          pass = $(rclone obscure $PW)" > nightly.conf
          pwd
      - run: mkdir nightly
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
      - run: |
          rclone --config=${{ github.workspace }}/nightly.conf mount nightly:/ nightly --daemon
          mkdir nightly/test
          ls -lra nightly