name: dispatch-test

on:
  workflow_dispatch:
  pull_request:
  
jobs:
  test:
    runs-on: windows-latest
   
    steps:
      - id: s1
        run: >
         echo "::set-output name=update_readme::asdasd%20%22asdasda%22asdasd%25%20asdasd%20%0Asadasdas"
      - run: |
         echo "${{ steps.s1.outputs.update_readme }}"
  test2:
    runs-on: macos-latest
   
    steps:
      - id: s1
        run: >
         echo "::set-output name=update_readme::asdasd%20%22asdasda%22asdasd%25%20asdasd%20%0Asadasdas"
      - run: |
         echo "${{ steps.s1.outputs.update_readme }}"
