name: dispatch-test

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
       - run: echo "head_ref: ${{ github.head_ref || 2}}"
       - run: echo "ref: ${{ github.ref || 2}}"
       
