name: dispatch-test

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
  
jobs:
  test:
    runs-on: ubuntu-latest
   
    steps:
       - name: Create Issue Comment
         uses: actions/github-script@v5
         with:
            script: |
              github.rest.issues.createComment({
                owner: "assignUser",
                repo: "test-repo-a",
                issue_number: 2,
                body: |
                  @assignUser It's time to renew your 'RRT_TOKEN'
                  - grant both repo and workflow access
                  - copy token to `pkgcheck-action` repo secrets
              })


