name: dispatch-test

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
  
jobs:
  test:
    runs-on: windows-latest
   
    steps:
      - id: s1
        run: |
         echo $GITHUB_PATH
         "/weird/path" | Add-Content -Path $GITHUB_PATH
      - run: echo $PATH
 

