name: test known hosts

on: 
  workflow_run:
    workflows: ["Dev PR"]
    types:
      - completed


jobs:
  build:
    name: test
    if: ${{ (github.event.workflow_run.conclusion == 'success' || 
              github.event_name == 'workflow_dispatch') 
          && github.repository == 'facebookincubator/velox' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github) }}"
