name: WebDav
on:
  push:
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "::warning file=test.R :: warning!"
          cd R
          echo "::warning file=lint_me.R :: warning!"
          #echo "::warning file=R/lint_me.R :: warning!"
