name: dispatch-test

on:
  workflow_dispatch:
  pull_request:
  
jobs:
  test:
    if: 1
    runs-on: ubuntu-latest
   
    steps:
      - id: s1
        run: >
         echo "::set-output name=update_readme::
         `git show --name-only --oneline |
           grep -c action.yaml |
           cat`"
      - run: |
         echo ${{ steps.s1.outputs.update_readme }}
      
