name: dispatch-test

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
  
jobs:
  test:
    runs-on: windows-latest
   
    steps:
      - id: s1
        run: |
         dir env:
 

