name: dispatch-test

on:
  workflow_dispatch:
  pull_request:
  
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SUPER_SECRET: "Mona The Octocat"
    steps:
      - uses: actions/checkout@v2
      - name: Trigger pkgcheck-action build
        run: |
          echo "::add-mask::$SUPER_SECRET"
          echo "Mona"
          echo  "Mona The Octocat"
          echo  Mona the Octocat
          echo "::warning file=test.R,line=1,endLine=3::Octolog makes it easy to create beautiful output in Github Action logs%0A%0A and use workflow commands in R.!"
        shell: bash
