name: test known hosts

on:
  workflow_dispatch:

  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Sync from Remote
        env:
          RSYNC_PATH: repo
          SSH_KEY: "${{ secrets.NIGHTLIES_RSYNC_KEY }}"
          PORT: "${{ secrets.NIGHTLIES_RSYNC_PORT }}"
          USER: "${{ secrets.NIGHTLIES_RSYNC_USER }}"
          HOST: "${{ secrets.NIGHTLIES_RSYNC_HOST }}"
          REMOTE_PATH: "${{ secrets.NIGHTLIES_RSYNC_PATH }}/arrow/r/src/contrib"
        run: |
            eval "$(ssh-agent)" > /dev/null
            echo "$SSH_KEY" | tr -d '\r' | DISPLAY=1 ssh-add - >/dev/null
            mkdir -p ~/.ssh
            echo "${{ secrets.NIGHTLIES_RSYNC_HOST_KEY }}" >> ~/.ssh/known_hosts

            # strict errors
            set -eu

            # Variables.
            RSYNC_SWITCHES="-avzrh --update --delete --progress "
            RSH="ssh -p $PORT"
            LOCAL_PATH="$GITHUB_WORKSPACE/$RSYNC_PATH"
            DSN="$USER@$HOST"

            # Deploy.
            sh -c "rsync $RSYNC_SWITCHES -e '$RSH' $DSN:$REMOTE_PATH/* $LOCAL_PATH"
      - run: tree repo

