name: dispatch-test

on:
  workflow_dispatch:
  pull_request:
  
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/ropensci-review-tools/pkgcheck-action

    steps:
      - uses: actions/checkout@v2
      - run: |
          options(cli.num_colors = crayon:::truecolor)
          cli::cli_alert_success("An Alert!") 
          cli::cli_alert_danger("An Alert!") 
        shell: Rscript {0}
