name: dispatch-test

on:
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
  
jobs:
  test:
    runs-on: windows-latest
   
    steps:
      - id: s1
        run: |
         "/a/new/path" | Add-Content -path $env:GITHUB_PATH;
         cat $env:GITHUB_PATH;
      - run: echo $env:PATH 
 

