name: WebDav
on:
  workflow_dispatch:

jobs:
  # test-linux:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: | 
  #         sudo apt update && sudo apt install davfs2
  #         mkdir nightly
  #         sudo bash -c 'echo "https://nightly.wujciak.de:8080 ${{ secrets.ASF_USER }} ${{ secrets.ASF_KEY }}" >> /etc/davfs2/secrets'
  #         sudo mount -t davfs https://nightly.wujciak.de:8080 nightly -o rw
  #         ls -la nightly
  test-mac:
    runs-on: macos-latest
    steps:
      - run: curl https://rclone.org/install.sh | sudo bash
      - name: Configure rclone
        env:
          PW: ${{ secrets.ASF_KEY }}
          USER: ${{ secrets.ASF_USER }}
        run: |
          echo "[nightly]
          type = webdav
          url = https://nightly.wujciak.de:8080
          vendor = other
          user = $USER
          pass = $(rclone obscure $PW)" > nightly.conf

          echo "RCLONE_CONFIG=${{ github.workspace }}/nightly.conf" >> $GITHUB_ENV
      # - uses: r-lib/actions/setup-r@v2
      #   with:
      #     install-r: false
      # - run: |
      #     install.packages("oskeyring")
      #     library(oskeyring)
      #     webdav <- macos_item("${{ secrets.ASF_KEY }}",
      #       attributes = list(
      #         port = 8080L,
      #         server = "nightly.wujciak.de",
      #         protocol = "https",
      #         account = "${{ secrets.ASF_USER }}",
      #         path = "/"
      #       ),
      #       class = "internet_password")
      #      webdav2 <- macos_item("${{ secrets.ASF_KEY }}",
      #       attributes = list(
      #         service = "https://nightly.wujciak.de:8080/",
      #         account = "${{ secrets.ASF_USER }}"
      #       ),
      #       class = "generic_password")
      #       macos_item_add(webdav)
      #       macos_item_add(webdav2)
      #       macos_keychain_list()
      #   shell: Rscript {0}
      # - name: Set up keychain
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     ASF_USER: ${{ secrets.ASF_USER }}
      #     ASF_KEY: ${{ secrets.ASF_KEY }}
      #   run: bash fix-keychain.sh
      - run: mkdir nightly
      - run: rclone mount nightly:/ nightly
      # - run: mount_webdav https://nightly.wujciak.de:8080/ ./nightly
      - run: ls nightly