name: test known hosts

on: 
  workflow_run:
    workflows: ["Dev PR"]
    types:
      - completed


jobs:
  build:
    name: test
    if: ${{ (github.event.workflow_run.conclusion == 'success' || 
              github.event_name == 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.workflow_run.pull_requests[0].number }}"
      - run: echo "${{ toJSON(github.event.workflow_run) }}"
