name: test known hosts

on: 
  workflow_run:
    workflows: ["Dev PR"]
    types:
      - completed


jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github.event.workflow) }}"