name: dispatch-test

on:
  workflow_dispatch:
  pull_request:
  
jobs:
  test:
    runs-on: ubuntu-latest
   
    steps:
      - uses: r-lib/actions/setup-r@v2
      - run: |
          Sys.setenv(COLORTERM = 'truecolor')
          install.packages("cli")
          cli::cli_alert_success("An Alert!") 
          print(isatty(stdout()))
         
          cli::cli_alert_danger("An Alert!") 
        shell: Rscript {0}
